#!/usr/bin/env sh

SCRIPTS_PATH=${SCRIPTS_PATH:=~/.config/yadm/scripts}
chmod +x ${SCRIPTS_PATH}/*

$SCRIPTS_PATH/install_zsh
$SCRIPTS_PATH/install_docker
$SCRIPTS_PATH/install_tailscale
$SCRIPTS_PATH/install_charmbracelet_tools
